#!/bin/sh

case "$1" in
    *.md)
        mdcat "$1"
        ;;
    *.csv)
        column -s, -t < "$1"
        ;;
    *.json)
        jq < "$1"
        ;;
    *.cbor)
        cbor2json.rb "$1"
        ;;
    *.pickle)
        python3 -m pickle "$1"
        ;;
    *)
        # We don't handle this format.
        exit 1
esac

# No further processing by lesspipe necessary
exit 0
